spring:
  application:
    name: demo-docker
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a87hp404a7420f8e8bcd0a7567c272e007b
    expiration: 60000 # 1 minute